# Generated by Django 3.1.14 on 2022-04-21 12:37

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='images/banners/')),
                ('status', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=20)),
            ],
            options={
                'verbose_name': '0. Баннер',
                'verbose_name_plural': '0. Баннеры',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/brands/')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': '2. Бренды',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': '1. Категории',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='images/colors/')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': '8. Цвета',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Страна Производства',
                'verbose_name_plural': ' 10. Страны Производства',
            },
        ),
        migrations.CreateModel(
            name='DoorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Тип двери',
                'verbose_name_plural': '5. Типы двери',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Главное Фото двери')),
                ('keywords', models.CharField(blank=True, default='Межкомнатные двери, двери, дверь, комнантые двери', max_length=255, null=True, verbose_name='Ключевые слова')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('amount', models.IntegerField(default=0, verbose_name='Количесво')),
                ('specification', ckeditor.fields.RichTextField(blank=True, default='\n    <table class="table">\n\t<tbody>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t<h5>Модель</h5>\n\t\t\t</td>\n\t\t\t<td>\n\t\t\t<h5>&nbsp;Лео</h5>\n\t\t\t</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t<p>Высота полотен</p>\n\t\t\t</td>\n\t\t\t<td>\n\t\t\t<h5>2000мм</h5>\n\t\t\t</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t<p>Ширина</p>\n\t\t\t</td>\n\t\t\t<td>\n\t\t\t<h5>600,700,800,900 мм</h5>\n\t\t\t</td>\n\t\t</tr>\n\t</tbody>\n</table>\n', null=True, verbose_name='Спецификация')),
                ('slug', models.SlugField(unique=True, verbose_name='Наименование Ссылки')),
                ('status', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.brand', verbose_name='Бренд')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Категория')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.country')),
            ],
            options={
                'verbose_name': 'Дверь',
                'verbose_name_plural': '3. Двери',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название')),
                ('services', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Сервисы')),
            ],
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Размер',
                'verbose_name_plural': '9. Размеры',
            },
        ),
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Фото')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
                ('sale_price', models.FloatField(blank=True, default=0, null=True, verbose_name='Цена по Скидке')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.color', verbose_name='Цвет')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Продукт')),
                ('size', models.ManyToManyField(to='shop.Sizes', verbose_name='Размеры')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.doortype', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Вариант',
                'verbose_name_plural': '4. Варианты',
            },
        ),
        migrations.CreateModel(
            name='RelatedImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
            options={
                'verbose_name': 'Детальная фото',
                'verbose_name_plural': '7. Детальные фото',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='services',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.service'),
        ),
    ]
