# Generated by Django 3.1.14 on 2022-05-08 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20220428_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Сервис', 'verbose_name_plural': 'Сервисы'},
        ),
    ]
